<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\PerfLab.Harness\PerfLab.Harness.csproj" />
    <ProjectReference Include="..\..\..\..\src\PerfLab.Harness.Raven\PerfLab.Harness.Raven.csproj" />
  </ItemGroup>
</Project>
